apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-app
spec:
  selector:
    matchLabels:
      app: back-app
  template:
    metadata:
      labels:
        app: back-app
    spec:
      containers:
      - name: back-app
        image: wbitt/network-multitool
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
