apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-myingress
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-myingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /{{ .Values.ingressPath }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-front-app-svc
            port:
              number: 80
      - path: /{{ .Values.ingressPath }}/api
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-back-app-svc
            port:
              number: 80


