apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-2-3-02-cfg # ИЗМЕНИТЕ: Укажите имя ConfigMap
data:
  # КЛЮЧЕВОЙ МОМЕНТ: index.html будет подключен как файл
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Страница из ConfigMap kolmykov kuber-homeworks  2.3</title> 
    </head>
    <body>
      <h1>Devops has you!</h1>
    </body>
    </html>
  default.conf: |
    server {
      listen 81;
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }
