apiVersion: v1
kind: Service
metadata:
  name: kube-1-3-app-svc
spec:
  selector:
    app: kube-1-3-app
  ports:
  - port: 80
    targetPort: 80
    name: nginx
  - port: 1180
    targetPort: 1180
    name: multitool
